version: 0.0
os: linux
files:
  - source: /dist
    destination: /home/ec2-user/metacamp_tg_bot
hooks:
# Install
  AfterIntall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root
# Validate Service
