version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/metacamp_tg_bot
  - source: /scripts
    destination: /home/ec2-user/metacamp_tg_bot/scripts
file_exists_behaviour: overwrite
hooks:
# Install
  ApplicationStop:
    - location: application_stop.sh
      timeout: 300
      runas: root
  AfterIntall:
    - location: after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: application_start.sh
      timeout: 300
      runas: root

