version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/metacamp_tg_bot
    file_exists_behaviour: overwrite
  - source: /scripts
    destination: /home/ec2-user/metacamp_tg_bot/scripts
    file_exists_behaviour: overwrite
hooks:
# Install
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: root
  AfterIntall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root

