version: 0.2

phases: 
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install typescript
      - npm install
  build:
    commands:
      - tsc --version
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
  discard-paths: yes