version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g typescript
      - npm install
  pre_build:
    commands:
      - echo "Nothing to do in the pre_build phase..."
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - cp appspec.yml dist/
      - cp -r scripts dist/
      - find /dist -type d
      - find /dist -type f
artifacts:
  files:
    - "dist/**/*"
    - "dist/**/**/*"
    - scripts/*
    - "**/*"
  discard-paths: no